---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: winhd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: win12r2vm1
  name: win12r2vm1
spec:
  dataVolumeTemplates:
  - metadata:
      name: win12r2vm1-dv
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi
      source:
          http:
            url: "https://kubevirt-iso.s3-us-west-1.amazonaws.com/Win2kR2.iso" 
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: win12r2vm1
    spec:
      domain:
        cpu:
          cores: 1
        devices:
          disks:
          - bootOrder: 1
            cdrom:
              bus: sata
            name: win12r2vm1-dv-disk
          - disk:
              bus: sata
            name: harddrive
        #machine:
          interfaces:
          - name: default
            bridge: {}
        resources:
          requests:
            memory: 1G
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - dataVolume:
          name: win12r2vm1-dv
        name: win12r2vm1-dv-disk
      - name: harddrive
        persistentVolumeClaim:
          claimName: winhd
